"""优先级引擎数据模型

定义文件优先级评估所需的枚举、数据类和配置。
"""

from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from src.utils.logger import get_logger

logger = get_logger(__name__)

"""文件优先级引擎模块

计算文件的扫描优先级，基于业务关键度、代码复杂度、安全敏感度和变更频率等多维度评分。
"""

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional

from .file_discovery import FileInfo, FileType, Language


class ExploitabilityLevel(Enum):
    HAS_PUBLIC_EXPLOIT_POC = ("has_public_exploit_poc", 1.0)
    HAS_EXPLOIT_CODE = ("has_exploit_code", 0.9)
    FUNCTIONALLY_VERIFIED = ("functionally_verified", 0.7)
    THEORY_POSSIBLE = ("theory_possible", 0.3)

    def __init__(self, label: str, score: float):
        self.label = label
        self.score = score


class ReachabilityLevel(Enum):
    PUBLIC_ENTRY_POINT = ("public_entry_point", 1.0)
    INTERNAL_INTERFACE = ("internal_interface", 0.6)
    DEEPLY_NESTED = ("deeply_nested", 0.3)
    UNREACHABLE = ("unreachable", 0.0)

    def __init__(self, label: str, score: float):
        self.label = label
        self.score = score


class AssetValueLevel(Enum):
    AUTH_PAYMENT = ("auth_payment", 1.0)
    BUSINESS_LOGIC = ("business_logic", 0.7)
    CONFIG_TOOLS = ("config_tools", 0.4)
    TEST_DOCS = ("test_docs", 0.1)

    def __init__(self, label: str, score: float):
        self.label = label
        self.score = score


@dataclass
class PriorityResult:
    real_risk_score: float
    cvss_base: float
    exploitability: float
    reachability: float
    asset_value: float
    priority_tier: str
    factors: Dict[str, Any] = field(default_factory=dict)


class ExploitabilityCalculator:
    @staticmethod
    def calculate(finding: Dict[str, Any]) -> float:
        exploit_info = finding.get("exploitability", "").lower()
        if "public" in exploit_info or "poc" in exploit_info:
            return ExploitabilityLevel.HAS_PUBLIC_EXPLOIT_POC.score
        elif "exploit" in exploit_info:
            return ExploitabilityLevel.HAS_EXPLOIT_CODE.score
        elif "verified" in exploit_info or "functional" in exploit_info:
            return ExploitabilityLevel.FUNCTIONALLY_VERIFIED.score
        return ExploitabilityLevel.THEORY_POSSIBLE.score

    @staticmethod
    def get_level(finding: Dict[str, Any]) -> ExploitabilityLevel:
        exploit_info = finding.get("exploitability", "").lower()
        if "public" in exploit_info or "poc" in exploit_info:
            return ExploitabilityLevel.HAS_PUBLIC_EXPLOIT_POC
        elif "exploit" in exploit_info:
            return ExploitabilityLevel.HAS_EXPLOIT_CODE
        elif "verified" in exploit_info or "functional" in exploit_info:
            return ExploitabilityLevel.FUNCTIONALLY_VERIFIED
        return ExploitabilityLevel.THEORY_POSSIBLE


class ReachabilityCalculator:
    @staticmethod
    def calculate(finding: Dict[str, Any]) -> float:
        reachability = finding.get("reachability", "").lower()
        if "public" in reachability or "entry" in reachability:
            return ReachabilityLevel.PUBLIC_ENTRY_POINT.score
        elif "internal" in reachability:
            return ReachabilityLevel.INTERNAL_INTERFACE.score
        elif "deep" in reachability or "nested" in reachability:
            return ReachabilityLevel.DEEPLY_NESTED.score
        return ReachabilityLevel.UNREACHABLE.score

    @staticmethod
    def get_level(finding: Dict[str, Any]) -> ReachabilityLevel:
        reachability = finding.get("reachability", "").lower()
        if "public" in reachability or "entry" in reachability:
            return ReachabilityLevel.PUBLIC_ENTRY_POINT
        elif "internal" in reachability:
            return ReachabilityLevel.INTERNAL_INTERFACE
        elif "deep" in reachability or "nested" in reachability:
            return ReachabilityLevel.DEEPLY_NESTED
        return ReachabilityLevel.UNREACHABLE


class AssetValueCalculator:
    @staticmethod
    def calculate(finding: Dict[str, Any]) -> float:
        asset_type = finding.get("asset_type", "").lower()
        if any(kw in asset_type for kw in ["auth", "payment", "credential", "password", "token"]):
            return AssetValueLevel.AUTH_PAYMENT.score
        elif any(kw in asset_type for kw in ["business", "logic", "core", "service"]):
            return AssetValueLevel.BUSINESS_LOGIC.score
        elif any(kw in asset_type for kw in ["config", "tool", "utility"]):
            return AssetValueLevel.CONFIG_TOOLS.score
        return AssetValueLevel.TEST_DOCS.score

    @staticmethod
    def get_level(finding: Dict[str, Any]) -> AssetValueLevel:
        asset_type = finding.get("asset_type", "").lower()
        if any(kw in asset_type for kw in ["auth", "payment", "credential", "password", "token"]):
            return AssetValueLevel.AUTH_PAYMENT
        elif any(kw in asset_type for kw in ["business", "logic", "core", "service"]):
            return AssetValueLevel.BUSINESS_LOGIC
        elif any(kw in asset_type for kw in ["config", "tool", "utility"]):
            return AssetValueLevel.CONFIG_TOOLS
        return AssetValueLevel.TEST_DOCS


class PriorityStrategy(Enum):
    """优先级策略"""

    BALANCED = "balanced"
    SECURITY_FIRST = "security_first"
    COMPLEXITY_FIRST = "complexity_first"
    BUSINESS_FIRST = "business_first"
    CHANGE_FREQUENCY_FIRST = "change_frequency_first"
    API_FIRST = "api_first"


class PriorityLevel(Enum):
    """优先级等级"""

    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFO = "info"


@dataclass
class FilePriority:
    """文件优先级信息"""

    file_info: FileInfo
    total_score: float
    business_score: float
    complexity_score: float
    security_score: float
    change_frequency_score: float
    priority_level: PriorityLevel
    rank: int = 0
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        """转换为字典"""
        return {
            "file_path": str(self.file_info.path),
            "total_score": self.total_score,
            "business_score": self.business_score,
            "complexity_score": self.complexity_score,
            "security_score": self.security_score,
            "change_frequency_score": self.change_frequency_score,
            "priority_level": self.priority_level.value,
            "rank": self.rank,
        }


@dataclass
class PriorityConfig:
    """优先级配置"""

    business_weight: float = 0.25
    complexity_weight: float = 0.25
    security_weight: float = 0.30
    change_frequency_weight: float = 0.20

    critical_threshold: float = 0.8
    high_threshold: float = 0.6
    medium_threshold: float = 0.4
    low_threshold: float = 0.2

    security_sensitive_patterns: List[str] = field(
        default_factory=lambda: [
            "auth",
            "login",
            "password",
            "credential",
            "token",
            "session",
            "api_key",
            "secret",
            "crypto",
            "encrypt",
            "decrypt",
            "hash",
            "salt",
            "permission",
            "privilege",
            "admin",
            "root",
            "sudo",
            "user",
            "account",
            "profile",
            "payment",
            "transaction",
            "order",
            "checkout",
            "cart",
            "invoice",
            "billing",
            "subscription",
            "license",
            "validation",
            "sanitize",
            "escape",
            "filter",
            "input",
            "output",
            "request",
            "response",
            "header",
            "cookie",
            "upload",
            "download",
            "file",
            "path",
            "url",
            "redirect",
            "forward",
            "proxy",
            "socket",
            "network",
            "database",
            "query",
            "sql",
            "nosql",
            "cache",
            "queue",
            "message",
            "event",
            "handler",
            "controller",
            "route",
            "endpoint",
            "api",
            "rest",
            "graphql",
            "rpc",
            "grpc",
            "soap",
            "wsdl",
            "xmlrpc",
            "callback",
            "webhook",
            "hook",
            "middleware",
            "interceptor",
            "filter",
            "guard",
            "shield",
            "barrier",
            "gate",
            "wall",
            "firewall",
            "waf",
            "ids",
            "ips",
            "siem",
            "log",
            "audit",
            "monitor",
            "alert",
            "notify",
            "report",
            "analytics",
            "tracking",
            "telemetry",
            "metric",
            "health",
            "status",
            "ping",
            "heartbeat",
        ]
    )

    business_critical_patterns: List[str] = field(
        default_factory=lambda: [
            "main",
            "app",
            "server",
            "client",
            "core",
            "engine",
            "manager",
            "service",
            "controller",
            "handler",
            "processor",
            "executor",
            "scheduler",
            "worker",
            "runner",
            "driver",
            "factory",
            "builder",
            "provider",
            "repository",
            "model",
            "entity",
            "schema",
            "mapper",
            "adapter",
            "connector",
            "client",
            "gateway",
            "proxy",
            "router",
            "dispatcher",
            "loader",
            "parser",
            "serializer",
            "validator",
            "converter",
            "transformer",
            "aggregator",
            "collector",
            "analyzer",
            "scanner",
            "checker",
            "detector",
            "finder",
            "searcher",
            "matcher",
            "filter",
            "sorter",
            "grouper",
            "partitioner",
            "splitter",
            "merger",
            "joiner",
            "composer",
            "assembler",
            "renderer",
            "generator",
            "producer",
            "consumer",
            "publisher",
            "subscriber",
            "listener",
            "observer",
            "watcher",
            "monitor",
            "supervisor",
            "coordinator",
            "orchestrator",
            "director",
            "leader",
            "master",
            "slave",
            "primary",
            "secondary",
            "backup",
            "failover",
            "recovery",
            "restore",
            "backup",
            "archive",
            "export",
            "import",
            "migration",
            "upgrade",
            "downgrade",
            "install",
            "uninstall",
            "setup",
            "teardown",
            "init",
            "destroy",
            "start",
            "stop",
            "restart",
            "reload",
            "refresh",
            "reset",
            "clear",
            "purge",
            "clean",
            "optimize",
            "compress",
            "decompress",
            "encode",
            "decode",
            "encrypt",
            "decrypt",
            "sign",
            "verify",
            "authenticate",
            "authorize",
            "login",
            "logout",
            "register",
            "deregister",
            "subscribe",
            "unsubscribe",
            "connect",
            "disconnect",
            "bind",
            "unbind",
            "attach",
            "detach",
            "mount",
            "unmount",
            "lock",
            "unlock",
            "acquire",
            "release",
            "allocate",
            "deallocate",
            "reserve",
            "commit",
            "rollback",
            "abort",
            "cancel",
            "undo",
            "redo",
            "revert",
            "apply",
            "reject",
            "approve",
            "confirm",
            "validate",
            "invalidate",
            "expire",
            "renew",
            "refresh",
            "update",
            "delete",
            "create",
            "read",
            "write",
            "append",
            "prepend",
            "insert",
            "modify",
            "replace",
            "swap",
            "exchange",
            "transfer",
            "move",
            "copy",
            "clone",
            "duplicate",
            "replicate",
            "sync",
            "async",
            "parallel",
            "serial",
            "batch",
            "stream",
            "flow",
            "pipeline",
            "chain",
            "sequence",
            "series",
            "loop",
            "iterate",
            "recurse",
            "traverse",
            "navigate",
            "explore",
            "discover",
            "detect",
            "identify",
            "recognize",
            "classify",
            "categorize",
            "tag",
            "label",
            "mark",
            "flag",
            "highlight",
            "annotate",
            "comment",
            "document",
            "describe",
            "explain",
            "illustrate",
            "demonstrate",
            "show",
            "hide",
            "display",
            "render",
            "paint",
            "draw",
            "plot",
            "chart",
            "graph",
            "visualize",
            "present",
            "format",
            "style",
            "design",
            "layout",
            "structure",
            "organize",
            "arrange",
            "order",
            "sort",
            "rank",
            "prioritize",
            "weight",
            "score",
            "rate",
            "grade",
            "assess",
            "evaluate",
            "measure",
            "quantify",
            "calculate",
            "compute",
            "estimate",
            "predict",
            "forecast",
            "project",
            "simulate",
            "model",
            "emulate",
            "imitate",
            "mock",
            "stub",
            "fake",
            "dummy",
            "test",
            "spec",
            "benchmark",
            "profile",
            "debug",
            "trace",
            "log",
            "audit",
            "inspect",
            "examine",
            "analyze",
            "review",
            "check",
            "verify",
            "validate",
            "ensure",
            "guarantee",
            "assert",
            "expect",
            "require",
            "demand",
            "enforce",
            "impose",
            "restrict",
            "limit",
            "constrain",
            "bound",
            "cap",
            "throttle",
            "rate_limit",
            "quota",
            "budget",
            "allocation",
            "reservation",
            "booking",
            "appointment",
            "schedule",
            "calendar",
            "timeline",
            "deadline",
            "due",
            "overdue",
            "pending",
            "queued",
            "processing",
            "running",
            "completed",
            "failed",
            "error",
            "warning",
            "info",
            "debug",
            "trace",
            "critical",
            "emergency",
            "alert",
            "urgent",
            "important",
            "normal",
            "low",
            "background",
            "foreground",
            "interactive",
            "batch",
            "scheduled",
            "manual",
            "automatic",
            "autonomous",
            "self",
            "auto",
            "smart",
            "intelligent",
            "adaptive",
            "dynamic",
            "static",
            "constant",
            "variable",
            "mutable",
            "immutable",
            "readonly",
            "writeonly",
            "readwrite",
            "volatile",
            "transient",
            "persistent",
            "temporary",
            "permanent",
            "ephemeral",
            "durable",
            "reliable",
            "unreliable",
            "available",
            "unavailable",
            "accessible",
            "inaccessible",
            "visible",
            "invisible",
            "public",
            "private",
            "protected",
            "internal",
            "external",
            "local",
            "global",
            "scope",
            "context",
            "environment",
            "setting",
            "preference",
            "option",
            "parameter",
            "argument",
            "variable",
            "constant",
            "literal",
            "expression",
            "statement",
            "block",
            "function",
            "method",
            "procedure",
            "routine",
            "subroutine",
            "program",
            "script",
            "module",
            "package",
            "library",
            "framework",
            "platform",
            "system",
            "application",
            "service",
            "daemon",
            "process",
            "thread",
            "task",
            "job",
            "work",
            "operation",
            "action",
            "command",
            "instruction",
            "directive",
            "rule",
            "policy",
            "strategy",
            "tactic",
            "plan",
            "design",
            "architecture",
            "pattern",
            "template",
            "blueprint",
            "schema",
            "model",
            "view",
            "controller",
            "presenter",
            "viewmodel",
            "adapter",
            "bridge",
            "facade",
            "proxy",
            "decorator",
            "composite",
            "flyweight",
            "observer",
            "mediator",
            "command",
            "chain",
            "iterator",
            "memento",
            "state",
            "strategy",
            "template",
            "visitor",
            "singleton",
            "factory",
            "builder",
            "prototype",
            "object_pool",
            "lazy",
            "eager",
            "async",
            "sync",
            "blocking",
            "nonblocking",
            "concurrent",
            "parallel",
            "distributed",
            "clustered",
            "replicated",
            "sharded",
            "partitioned",
            "segmented",
            "fragmented",
            "chunked",
            "batched",
            "streamed",
            "piped",
            "channeled",
            "queued",
            "buffered",
            "cached",
            "memoized",
            "indexed",
            "hashed",
            "sorted",
            "ordered",
            "grouped",
            "aggregated",
            "summarized",
            "compressed",
            "encoded",
            "encrypted",
            "signed",
            "certified",
            "verified",
            "validated",
            "authenticated",
            "authorized",
            "permitted",
            "allowed",
            "granted",
            "denied",
            "rejected",
            "blocked",
            "filtered",
            "screened",
            "sanitized",
            "cleaned",
            "purified",
            "refined",
            "polished",
            "optimized",
            "improved",
            "enhanced",
            "upgraded",
            "updated",
            "patched",
            "fixed",
            "repaired",
            "restored",
            "recovered",
            "reconstructed",
            "rebuilt",
            "refactored",
            "rewritten",
            "redesigned",
            "reimplemented",
            "replaced",
            "substituted",
            "swapped",
            "exchanged",
            "converted",
            "transformed",
            "translated",
            "interpreted",
            "compiled",
            "built",
            "packaged",
            "deployed",
            "released",
            "published",
            "distributed",
            "delivered",
            "installed",
            "configured",
            "initialized",
            "started",
            "launched",
            "executed",
            "run",
            "processed",
            "handled",
            "served",
            "responded",
            "replied",
            "acknowledged",
            "confirmed",
            "accepted",
            "approved",
            "authorized",
            "permitted",
            "enabled",
            "activated",
            "triggered",
            "fired",
            "invoked",
            "called",
            "requested",
            "demanded",
            "required",
            "needed",
            "wanted",
            "desired",
            "expected",
            "anticipated",
            "predicted",
            "forecasted",
            "projected",
            "estimated",
            "calculated",
            "computed",
            "determined",
            "decided",
            "chosen",
            "selected",
            "picked",
            "elected",
            "nominated",
            "appointed",
            "assigned",
            "allocated",
            "distributed",
            "shared",
            "divided",
            "split",
            "separated",
            "isolated",
            "quarantined",
            "sandboxed",
            "containerized",
            "virtualized",
            "abstracted",
            "encapsulated",
            "wrapped",
            "packaged",
            "bundled",
            "grouped",
            "clustered",
            "categorized",
            "classified",
            "labeled",
            "tagged",
            "marked",
            "flagged",
            "highlighted",
            "emphasized",
            "stressed",
            "prioritized",
            "ranked",
            "ordered",
            "sorted",
            "arranged",
            "organized",
            "structured",
            "formatted",
            "styled",
            "designed",
            "rendered",
            "displayed",
            "shown",
            "presented",
            "exposed",
            "published",
            "released",
            "distributed",
            "shared",
            "communicated",
            "transmitted",
            "sent",
            "delivered",
            "received",
            "accepted",
            "processed",
            "handled",
            "consumed",
            "used",
            "utilized",
            "exploited",
            "leveraged",
            "capitalized",
            "benefited",
            "profited",
            "gained",
            "won",
            "achieved",
            "accomplished",
            "completed",
            "finished",
            "done",
            "ended",
            "terminated",
            "stopped",
            "halted",
            "paused",
            "suspended",
            "deferred",
            "postponed",
            "delayed",
            "waited",
            "slept",
            "idle",
            "inactive",
            "dormant",
            "hibernating",
            "frozen",
            "locked",
            "blocked",
            "disabled",
            "deactivated",
            "inactive",
            "offline",
            "disconnected",
            "unavailable",
            "missing",
            "lost",
            "deleted",
            "removed",
            "cleared",
            "purged",
            "destroyed",
            "killed",
            "terminated",
            "aborted",
            "cancelled",
            "revoked",
            "retracted",
            "withdrawn",
            "rejected",
            "denied",
            "refused",
            "declined",
            "dismissed",
            "ignored",
            "skipped",
            "omitted",
            "excluded",
            "filtered",
            "screened",
            "blocked",
            "prohibited",
            "forbidden",
            "banned",
            "restricted",
            "limited",
            "constrained",
            "bound",
            "tied",
            "chained",
            "linked",
            "connected",
            "associated",
            "related",
            "referenced",
            "pointed",
            "directed",
            "targeted",
            "aimed",
            "focused",
            "centered",
            "oriented",
            "aligned",
            "synchronized",
            "coordinated",
            "orchestrated",
            "managed",
            "controlled",
            "governed",
            "regulated",
            "supervised",
            "monitored",
            "observed",
            "watched",
            "tracked",
            "traced",
            "logged",
            "recorded",
            "documented",
            "reported",
            "notified",
            "alerted",
            "warned",
            "informed",
            "updated",
            "notified",
            "messaged",
            "emailed",
            "sent",
            "delivered",
            "received",
            "read",
            "seen",
            "viewed",
            "opened",
            "clicked",
            "tapped",
            "pressed",
            "touched",
            "swiped",
            "scrolled",
            "zoomed",
            "panned",
            "rotated",
            "scaled",
            "resized",
            "moved",
            "dragged",
            "dropped",
            "placed",
            "positioned",
            "located",
            "found",
            "discovered",
            "detected",
            "identified",
            "recognized",
            "authenticated",
            "verified",
            "validated",
            "confirmed",
            "approved",
            "accepted",
            "authorized",
            "permitted",
            "allowed",
            "enabled",
            "activated",
            "started",
            "initiated",
            "launched",
            "executed",
            "run",
            "processed",
            "handled",
            "served",
            "completed",
            "finished",
            "done",
        ]
    )
