export { default as IDEPanel } from './IDEMainPanel'
export { default as CodeViewer } from './CodeViewer'
export { default as VulnTimeline } from './VulnTimeline'
export { default as FixSuggestions } from './FixSuggestions'
export { detectLanguage } from './CodeViewer'
export type { VulnItem, FixSuggestion, IDEFileData } from './types'
